name: Hello world

on:
  push:
    branches: ["main"]

jobs:
  hello-world:
    runs-on: 192.168.28.128
    steps:
      - uses: actions/checkout@v3
      
      - name: Hello world
        shell: bash
        run: |
          echo "Hey Do this"
          cp ./MyWork
          cp test.sh /tmp/test.sh
