name: Hello world

on:
  push:
    branches: ["main"]

jobs:
  hello-world:
    runs-on: slef-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Hello world
        shell: bash
        run: |
          echo "Hey Do this"
          cp ./MyWork
          cp test.sh /tmp/test.sh
