name: Hello world

on:
  push:
    branches: ["main"]

jobs:
  hello-world:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      
      - name: Hello world
        shell: bash
        run: |
          echo "Hello Ahmad and Maryam"
