name: Hello world

on:
  push:
    branches: ["main"]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Hello world
        shell: bash
        run: |
          echo "Hey Do this"
          cp ./MyWork/test.sh /tmp/test.sh
