oname: Hello world

on: [push]

jobs:
  hello-world:
    runs-on: 'self-hosted', 'Linux', 'X64'
    steps:
      - name: Hello world
        run: |
          echo "Hello World"
          echo "I love Merab"
