name: Hello world

on: [push]
    branches: ["main"]

jobs:
  run-list:
    runs-on: 'self-hosted', 'Linux', 'X64'
    steps:
      - name: Hello world
        run: |
          echo "Hello World"
          echo "I love Merab"
